GET http://localhost:3000/notes
Content-Type: application/json

###
GET http://localhost:3000/notes/1
Content-Type: application/json

###
POST http://localhost:3000/note/new
Content-Type: application/json

{
    "title": "Express data",
    "content": "This came from express"
}